<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Alumni;
use Illuminate\Support\Facades\Hash;

class AlumniSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Alumni::insert([
            [
                'alumni_id' => 1,
                'level_id' => 2,
                'nama' => 'Kayla Putri Amelia',
                'NIM' => '2341760103',
                'tahun_lulus' => '2022',
                'password' => Hash::make('123456'),
                'prodi_id' => 1,
                'no_hp' => '081234567890',
                'email' => 'kayla.amelia@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 2,
                'level_id' => 2,
                'nama' => 'Intan Firdausi',
                'NIM' => '2341760185',
                'tahun_lulus' => '2020',
                'password' => Hash::make('123456'),
                'prodi_id' => 2,
                'no_hp' => '081234567891',
                'email' => 'intanfir27@gmail.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 3,
                'level_id' => 2,
                'nama' => 'Kaka Dwi Saputra',
                'NIM' => '2341760005',
                'tahun_lulus' => '2019',
                'password' => Hash::make('123456'),
                'prodi_id' => 1,
                'no_hp' => '081234567892',
                'email' => 'scarlletaja27@gmail.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 4,
                'level_id' => 2,
                'nama' => 'Nadia Fitria Permatasari',
                'NIM' => '2341760104',
                'tahun_lulus' => '2021',
                'password' => Hash::make('123456'),
                'prodi_id' => 3,
                'no_hp' => '081234567893',
                'email' => 'nadia.permatasari@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 5,
                'level_id' => 2,
                'nama' => 'Dina Ayu Prameswari',
                'NIM' => '2341760105',
                'tahun_lulus' => '2023',
                'password' => Hash::make('123456'),
                'prodi_id' => 2,
                'no_hp' => '081234567894',
                'email' => 'dina.prameswari@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 6,
                'level_id' => 2,
                'nama' => 'Rama Yudha Wiratama',
                'NIM' => '2341760106',
                'tahun_lulus' => '2020',
                'password' => Hash::make('123456'),
                'prodi_id' => 1,
                'no_hp' => '081234567895',
                'email' => 'rama.wiratama@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 7,
                'level_id' => 2,
                'nama' => 'Putri Nadhifa Maharani',
                'NIM' => '2341760107',
                'tahun_lulus' => '2018',
                'password' => Hash::make('123456'),
                'prodi_id' => 3,
                'no_hp' => '081234567896',
                'email' => 'putri.maharani@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 8,
                'level_id' => 2,
                'nama' => 'Budi Setiawan Hidayat',
                'NIM' => '2341760108',
                'tahun_lulus' => '2022',
                'password' => Hash::make('123456'),
                'prodi_id' => 2,
                'no_hp' => '081234567897',
                'email' => 'budi.hidayat@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 9,
                'level_id' => 2,
                'nama' => 'Siti Nurhaliza Zahra',
                'NIM' => '2341760109',
                'tahun_lulus' => '2023',
                'password' => Hash::make('123456'),
                'prodi_id' => 1,
                'no_hp' => '081234567898',
                'email' => 'siti.zahra@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 10,
                'level_id' => 2,
                'nama' => 'Dewi Anjani Safitri',
                'NIM' => '2341760110',
                'tahun_lulus' => '2021',
                'password' => Hash::make('123456'),
                'prodi_id' => 3,
                'no_hp' => '081234567899',
                'email' => 'dewi.safitri@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 11,
                'level_id' => 2,
                'nama' => 'Galih Putra Pangestu',
                'NIM' => '2341760111',
                'tahun_lulus' => '2019',
                'password' => Hash::make('123456'),
                'prodi_id' => 2,
                'no_hp' => '081234567800',
                'email' => 'galih.pangestu@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 12,
                'level_id' => 2,
                'nama' => 'Rina Amelia Lestari',
                'NIM' => '2341760112',
                'tahun_lulus' => '2022',
                'password' => Hash::make('123456'),
                'prodi_id' => 3,
                'no_hp' => '081234567801',
                'email' => 'rina.lestari@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 13,
                'level_id' => 2,
                'nama' => 'Agus Wibowo Santoso',
                'NIM' => '2341760113',
                'tahun_lulus' => '2020',
                'password' => Hash::make('123456'),
                'prodi_id' => 1,
                'no_hp' => '081234567802',
                'email' => 'agus.santoso@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 14,
                'level_id' => 2,
                'nama' => 'Lisa Maharani Dewi',
                'NIM' => '2341760114',
                'tahun_lulus' => '2023',
                'password' => Hash::make('123456'),
                'prodi_id' => 2,
                'no_hp' => '081234567803',
                'email' => 'lisa.dewi@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 15,
                'level_id' => 2,
                'nama' => 'Andi Prasetyo Wijaya',
                'NIM' => '2341760115',
                'tahun_lulus' => '2022',
                'password' => Hash::make('123456'),
                'prodi_id' => 3,
                'no_hp' => '081234567804',
                'email' => 'andi.wijaya@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 16,
                'level_id' => 2,
                'nama' => 'Riko Ananda Putra',
                'NIM' => '2341760116',
                'tahun_lulus' => '2021',
                'password' => Hash::make('123456'),
                'prodi_id' => 2,
                'no_hp' => '081234567805',
                'email' => 'riko.putra@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 17,
                'level_id' => 2,
                'nama' => 'Lia Kusuma Wardhani',
                'NIM' => '2341760117',
                'tahun_lulus' => '2018',
                'password' => Hash::make('123456'),
                'prodi_id' => 1,
                'no_hp' => '081234567806',
                'email' => 'lia.wardhani@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 18,
                'level_id' => 2,
                'nama' => 'Bagas Pramudya Utama',
                'NIM' => '2341760118',
                'tahun_lulus' => '2020',
                'password' => Hash::make('123456'),
                'prodi_id' => 3,
                'no_hp' => '081234567807',
                'email' => 'bagas.utama@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 19,
                'level_id' => 2,
                'nama' => 'Mega Rahayu Putri',
                'NIM' => '2341760119',
                'tahun_lulus' => '2023',
                'password' => Hash::make('123456'),
                'prodi_id' => 2,
                'no_hp' => '081234567808',
                'email' => 'mega.putri@example.com',
                'foto' => null,
            ],
            [
                'alumni_id' => 20,
                'level_id' => 2,
                'nama' => 'Dimas Aditya Nugroho',
                'NIM' => '2341760120',
                'tahun_lulus' => '2021',
                'password' => Hash::make('123456'),
                'prodi_id' => 1,
                'no_hp' => '081234567809',
                'email' => 'dimas.nugroho@example.com',
                'foto' => null,
            ],
        ]);
    }
}
